# Generated by Django 4.1.3 on 2023-01-30 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0008_alter_tourism_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tourism",
            options={"ordering": ["-name"]},
        ),
    ]
